// Regenerates src/registry.generated.ts from brand.manifest.json + assets/**.svg.
//
// Mirrors the icon-registry pattern: the .json + raw SVGs are the source of truth;
// the generated .ts inlines them so consumers ship no raw assets and need no SVG
// loader. CI re-runs this and fails if the committed output drifts.
//
//   node scripts/sync.mjs
//
// An art slot in the manifest is either "pending" or a path relative to assets/.
// For each non-pending slot we read the file and inline its (trimmed) contents,
// keyed `${id}:${kind}:${tone}`. Missing files are reported and treated as pending
// so the build never breaks on a not-yet-delivered master.

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const pkgRoot = resolve(here, '..');
const manifestPath = resolve(pkgRoot, 'brand.manifest.json');
const assetsDir = resolve(pkgRoot, 'assets');
const outPath = resolve(pkgRoot, 'src/registry.generated.ts');

const manifest = JSON.parse(readFileSync(manifestPath, 'utf8'));

/** @type {Record<string, string>} */
const art = {};
const missing = [];
let resolved = 0;

for (const logo of manifest.logos) {
  for (const [kind, tones] of Object.entries(logo.variants)) {
    for (const [tone, slot] of Object.entries(tones)) {
      if (slot === 'pending' || !slot) continue;
      const file = resolve(assetsDir, slot);
      if (!existsSync(file)) {
        missing.push(`${logo.id}:${kind}:${tone} → ${slot}`);
        continue;
      }
      art[`${logo.id}:${kind}:${tone}`] = readFileSync(file, 'utf8').trim();
      resolved += 1;
    }
  }
}

const header = `// AUTO-GENERATED by scripts/sync.mjs — do not edit by hand.
// Source: brand.manifest.json + assets/**.svg. Run \`pnpm --filter @auxiliary/brand sync\`.
`;

const body = `${header}
export const MANIFEST = ${JSON.stringify(manifest, null, 2)} as const;

/** Inlined SVG markup keyed \`\${id}:\${kind}:\${tone}\`. Empty until masters land in assets/. */
export const ART: Record<string, string> = ${JSON.stringify(art, null, 2)};
`;

writeFileSync(outPath, body);

console.log(`[brand] sync: ${resolved} art slot(s) inlined, ${Object.keys(art).length} key(s).`);
if (missing.length) {
  console.warn(`[brand] sync: ${missing.length} referenced master(s) missing (treated as pending):`);
  for (const m of missing) console.warn(`  - ${m}`);
}
