/**
 * Curated allow-list of icons that @auxiliary/icons ships.
 *
 * This file is the source of truth for *what* is in the registry. The actual
 * SVG data lives in src/registry.ts and is regenerated by `pnpm sync`.
 *
 * Every entry is file-sourced from inputs/. Two layouts are supported:
 *   - inputs/<file>.svg           — single shape, rendered at every weight
 *   - inputs/<weight>/<file>.svg  — per-weight shapes (thin/light/regular/solid)
 *
 * The package has no dependency on any icon vendor: sync reads SVG files off
 * disk, and the generated registry carries only static path data.
 */

export type IconWeight = 'thin' | 'light' | 'regular' | 'solid';

export interface IconSpec {
  /** Name exposed to consumers via the typed `name` prop. */
  name: string;
  /** Filename in inputs/ (without .svg). Defaults to `name`. */
  file?: string;
}

/**
 * The shipped set.
 *
 * Keep this list tight. Restraint over reach (CLAUDE.md principle 3).
 * Adding an icon = a maintenance commitment to every weight + every theme.
 */
export const ICONS: IconSpec[] = [
  // Navigation
  { name: 'chevron-up' },
  { name: 'chevron-down' },
  { name: 'chevron-left' },
  { name: 'chevron-right' },
  { name: 'arrow-up' },
  { name: 'arrow-down' },
  { name: 'arrow-left' },
  { name: 'arrow-right' },

  // Action / control
  { name: 'xmark' },
  { name: 'check' },
  { name: 'plus' },
  { name: 'minus' },
  { name: 'bars' },
  { name: 'ellipsis' },
  { name: 'ellipsis-vertical' },
  { name: 'magnifying-glass' },
  { name: 'gear' },
  { name: 'arrow-up-right-from-square' },
  { name: 'copy' },
  { name: 'trash' },
  { name: 'pen-to-square' },

  // Status / feedback (paired with the 5-level alarm hierarchy in @auxiliary/tokens)
  { name: 'circle-check' },
  { name: 'circle-xmark' },
  { name: 'circle-info' },
  { name: 'circle-question' },
  { name: 'circle-exclamation' },
  { name: 'triangle-exclamation' },
  { name: 'octagon-exclamation' },

  // Identity / state
  { name: 'user' },
  { name: 'users' },
  { name: 'bell' },
  { name: 'house' },
  { name: 'eye' },
  { name: 'eye-slash' },
  { name: 'lock' },
  { name: 'lock-open' },

  // Auterion operational glyphs
  { name: 'drone' },
];
