/**
 * Curated allow-list of icons that @auxiliary/icons ships.
 *
 * This file is the source of truth for *what* is in the registry. The actual
 * SVG data lives in src/registry.ts and is regenerated by `pnpm sync`.
 *
 * Two sources:
 *   - `fa` entries are pulled from Font Awesome Pro Sharp (Solid/Regular/Light/Thin)
 *     at sync time. The runtime carries no FA dependency — only the static path data.
 *   - `custom` entries are read from inputs/<name>.svg — hand-authored Auterion glyphs
 *     for operational concepts that have no FA equivalent (drone, geofence, RTL, etc.).
 */

export type FaWeight = 'thin' | 'light' | 'regular' | 'solid';

export interface FaIconSpec {
  /** Name exposed to consumers via the typed `name` prop. */
  name: string;
  /** Font Awesome icon identifier (e.g. "chevron-right"). */
  fa: string;
  /** Which weights to include. Defaults to all four. */
  weights?: FaWeight[];
}

export interface CustomIconSpec {
  /** Name exposed to consumers via the typed `name` prop. */
  name: string;
  /** Filename in inputs/ (without .svg). Defaults to `name`. */
  file?: string;
}

/**
 * Font Awesome Pro Sharp glyphs.
 *
 * Keep this list tight. Restraint over reach (CLAUDE.md principle 3).
 * Adding an icon = a maintenance commitment to every weight + every theme.
 */
export const FA_ICONS: FaIconSpec[] = [
  // Navigation
  { name: 'chevron-up', fa: 'chevron-up' },
  { name: 'chevron-down', fa: 'chevron-down' },
  { name: 'chevron-left', fa: 'chevron-left' },
  { name: 'chevron-right', fa: 'chevron-right' },
  { name: 'arrow-up', fa: 'arrow-up' },
  { name: 'arrow-down', fa: 'arrow-down' },
  { name: 'arrow-left', fa: 'arrow-left' },
  { name: 'arrow-right', fa: 'arrow-right' },

  // Action / control
  { name: 'xmark', fa: 'xmark' },
  { name: 'check', fa: 'check' },
  { name: 'plus', fa: 'plus' },
  { name: 'minus', fa: 'minus' },
  { name: 'bars', fa: 'bars' },
  { name: 'ellipsis', fa: 'ellipsis' },
  { name: 'ellipsis-vertical', fa: 'ellipsis-vertical' },
  { name: 'magnifying-glass', fa: 'magnifying-glass' },
  { name: 'gear', fa: 'gear' },
  { name: 'arrow-up-right-from-square', fa: 'arrow-up-right-from-square' },
  { name: 'copy', fa: 'copy' },
  { name: 'trash', fa: 'trash' },
  { name: 'pen-to-square', fa: 'pen-to-square' },

  // Status / feedback (paired with the 5-level alarm hierarchy in @auxiliary/tokens)
  { name: 'circle-check', fa: 'circle-check' },
  { name: 'circle-xmark', fa: 'circle-xmark' },
  { name: 'circle-info', fa: 'circle-info' },
  { name: 'circle-question', fa: 'circle-question' },
  { name: 'circle-exclamation', fa: 'circle-exclamation' },
  { name: 'triangle-exclamation', fa: 'triangle-exclamation' },
  { name: 'octagon-exclamation', fa: 'octagon-exclamation' },

  // Identity / state
  { name: 'user', fa: 'user' },
  { name: 'users', fa: 'users' },
  { name: 'bell', fa: 'bell' },
  { name: 'house', fa: 'house' },
  { name: 'eye', fa: 'eye' },
  { name: 'eye-slash', fa: 'eye-slash' },
  { name: 'lock', fa: 'lock' },
  { name: 'lock-open', fa: 'lock-open' },
];

/**
 * Auterion operational glyphs. Each entry corresponds to a file under inputs/.
 *
 * Custom icons have a single shape (no weight variants). The `weight` prop on
 * <Icon> is ignored for these — they render the same regardless.
 */
export const CUSTOM_ICONS: CustomIconSpec[] = [
  { name: 'drone' },
];
