#!/usr/bin/env node
/**
 * Generate the design agent team from design-team/roster.md.
 *
 * roster.md is the single source of truth. This script emits:
 *   .claude/agents/<slug>.md        Claude Code / Cowork subagents (tier: repo only)
 *   design-team/dist/personas.md    paste-ready personas for Claude Projects / any platform
 *   .crystl/heroes/<slug>.json      crystl Local Hero files (all roles)
 *
 * Heroes emit straight into `.crystl/heroes/` because that is the only path crystl loads
 * project-local heroes from — staging them elsewhere means they never take effect.
 *
 * Usage:
 *   node design-team/build.mjs            write files
 *   node design-team/build.mjs --check    verify outputs are in sync, exit 1 if not
 */

import { readFileSync, writeFileSync, mkdirSync, rmSync, existsSync, readdirSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, '..');
const ROSTER = join(HERE, 'roster.md');
const CHECK = process.argv.includes('--check');

/** Full model strings, resolved from the short aliases used in roster.md. */
const MODELS = {
  opus: 'claude-opus-5',
  sonnet: 'claude-sonnet-5',
  haiku: 'claude-haiku-4-5-20251001',
};

// ---------------------------------------------------------------- parse

const src = readFileSync(ROSTER, 'utf8');

/** Shared context = everything between the "## Shared context" heading and the first role. */
function extractShared(text) {
  const start = text.indexOf('## Shared context');
  if (start === -1) throw new Error('roster.md: missing "## Shared context" section');
  const end = text.search(/\n## 1\. /);
  if (end === -1) throw new Error('roster.md: missing "## 1. <role>" heading');
  return text
    .slice(start, end)
    .replace(/^## Shared context\s*/, '')
    .replace(/\n---\n[\s\S]*$/, '') // drop trailing convention/tier sections
    .trim();
}

/** Roles are "## <n>. <Name>" followed by a ```json meta block and a "### Persona" body. */
function extractRoles(text) {
  const chunks = text.split(/\n## (?=\d+\. )/).slice(1);
  return chunks.map((chunk) => {
    const name = chunk.match(/^\d+\.\s*(.+)/)?.[1]?.trim();
    if (!name) throw new Error(`roster.md: unnamed role in chunk starting "${chunk.slice(0, 40)}"`);

    const json = chunk.match(/```json\n([\s\S]*?)\n```/)?.[1];
    if (!json) throw new Error(`roster.md: role "${name}" has no \`\`\`json meta block`);

    let meta;
    try {
      meta = JSON.parse(json);
    } catch (err) {
      throw new Error(`roster.md: role "${name}" has invalid JSON meta — ${err.message}`);
    }

    const persona = chunk.split(/### Persona\n/)[1]?.trim();
    if (!persona) throw new Error(`roster.md: role "${name}" has no "### Persona" section`);

    for (const key of ['slug', 'tier', 'model', 'mandate', 'trigger', 'charter', 'writes', 'tools']) {
      if (meta[key] === undefined) throw new Error(`roster.md: role "${name}" missing "${key}"`);
    }
    if (!['repo', 'advisory'].includes(meta.tier)) {
      throw new Error(`roster.md: role "${name}" has tier "${meta.tier}" (want repo|advisory)`);
    }
    if (!MODELS[meta.model]) {
      throw new Error(
        `roster.md: role "${name}" has model "${meta.model}" (want ${Object.keys(MODELS).join('|')})`,
      );
    }
    return { name, persona, ...meta };
  });
}

const shared = extractShared(src);
const roles = extractRoles(src);

// ---------------------------------------------------------------- validate

const problems = [];

if (roles.length !== 10) problems.push(`expected 10 roles, found ${roles.length}`);

const slugs = new Set();
for (const r of roles) {
  if (slugs.has(r.slug)) problems.push(`duplicate slug "${r.slug}"`);
  slugs.add(r.slug);
  if (!/^[a-z0-9-]+$/.test(r.slug)) problems.push(`slug "${r.slug}" must be kebab-case`);
  if (r.tier === 'advisory' && r.writes.length) {
    problems.push(`"${r.name}" is advisory but declares writes: ${r.writes.join(', ')}`);
  }
  if (r.tier === 'repo' && !r.writes.length) {
    problems.push(`"${r.name}" is repo tier but declares no writes`);
  }
}

// No two repo roles may claim the same write path.
const claimed = new Map();
for (const r of roles.filter((x) => x.tier === 'repo')) {
  for (const path of r.writes) {
    if (claimed.has(path)) {
      problems.push(`write collision on "${path}": ${claimed.get(path)} and ${r.name}`);
    }
    claimed.set(path, r.name);
  }
}

if (problems.length) {
  console.error('roster.md validation failed:');
  for (const p of problems) console.error(`  - ${p}`);
  process.exit(1);
}

// ---------------------------------------------------------------- render

const BANNER = 'Generated by design-team/build.mjs from design-team/roster.md. Do not edit.';

/**
 * Flatten a string into a safe single-line YAML plain scalar: collapse whitespace and
 * strip characters that would need quoting or change the parse (`"`, `'`, `:`, `#`).
 */
function yamlScalar(s) {
  const flat = s.replace(/\s+/g, ' ').replace(/["']/g, '').replace(/\s*:\s*/g, ' — ').replace(/#/g, '').trim();
  if (/^[-?|>@`&*!%]/.test(flat)) throw new Error(`unsafe leading char in YAML scalar: "${flat}"`);
  return flat;
}

/** A repo-tier role becomes a Claude Code subagent. */
function renderSubagent(r) {
  return `---
name: ${r.slug}
description: ${yamlScalar(`${r.mandate} ${r.trigger}`)}
model: ${r.model}
tools: ${r.tools.join(', ')}
---

<!-- ${BANNER} -->

# ${r.name}

${r.persona}

## Charter

- **Protects:** ${r.charter.protects}
- **Challenges:** ${r.charter.challenges}
- **Won't compromise:** ${r.charter.wont_compromise}

## Paths you may write

${r.writes.map((w) => `- \`${w}\``).join('\n')}

Everything else in this repo is read-only to you. When work needs a change outside these paths,
report it as a finding with the exact expected value — do not reach across the boundary.

---

# Shared context

${shared}
`;
}

/** Every role gets a paste-ready persona block. */
function renderPersonas() {
  const body = roles
    .map(
      (r) => `## ${r.name}

- **Tier:** ${r.tier}
- **Model:** ${r.model} (\`${MODELS[r.model]}\`)
- **Mandate:** ${r.mandate}
- **Use when:** ${r.trigger}
- **Protects:** ${r.charter.protects}
- **Challenges:** ${r.charter.challenges}
- **Won't compromise:** ${r.charter.wont_compromise}

\`\`\`text
${r.persona}
\`\`\`
`,
    )
    .join('\n');

  return `# Design team personas — paste-ready

<!-- ${BANNER} -->

Each block below is self-contained enough to drop into a system-prompt or description field.
For best results, prepend the shared context at the bottom of this file.

${body}
---

# Shared context (prepend to any persona)

\`\`\`text
${shared}
\`\`\`
`;
}

/** crystl Local Hero JSON. Uses full model strings — crystl has no alias support. */
function renderHero(r) {
  return `${JSON.stringify(
    {
      role_name: r.name,
      guardrail: Boolean(r.guardrail),
      instructions: r.persona.replace(/\s*\n\s*/g, ' ').trim(),
      personality: r.personality ?? '',
      charter: r.charter,
      stats: r.stats ?? { strength: 6, intelligence: 8, wisdom: 7, dexterity: 6 },
      model: MODELS[r.model],
      agent: 'claude',
    },
    null,
    2,
  )}\n`;
}

// ---------------------------------------------------------------- emit

const HEROES_DIR = join(ROOT, '.crystl/heroes');

const outputs = new Map();

for (const r of roles.filter((x) => x.tier === 'repo')) {
  outputs.set(join(ROOT, '.claude/agents', `${r.slug}.md`), renderSubagent(r));
}
outputs.set(join(HERE, 'dist/personas.md'), renderPersonas());
for (const r of roles) {
  outputs.set(join(HEROES_DIR, `${r.slug}.json`), renderHero(r));
}

if (CHECK) {
  const stale = [];
  for (const [path, content] of outputs) {
    if (!existsSync(path) || readFileSync(path, 'utf8') !== content) {
      stale.push(path.replace(`${ROOT}/`, ''));
    }
  }
  if (stale.length) {
    console.error('Generated design-team outputs are stale. Run: node design-team/build.mjs');
    for (const s of stale) console.error(`  - ${s}`);
    process.exit(1);
  }
  console.log(`design-team: ${outputs.size} generated files in sync.`);
  process.exit(0);
}

for (const [path, content] of outputs) {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
}

// Prune hero files for roles that no longer exist. Best-effort: some mounts disallow unlink,
// and a stale extra file is not worth failing the build over.
const expectedHeroes = new Set(roles.map((r) => `${r.slug}.json`));
for (const file of readdirSync(HEROES_DIR)) {
  if (file.endsWith('.json') && !expectedHeroes.has(file)) {
    try {
      rmSync(join(HEROES_DIR, file));
      console.log(`  pruned stale hero: ${file}`);
    } catch (err) {
      console.warn(`  warning: could not prune stale hero ${file} — ${err.code ?? err.message}`);
    }
  }
}

// Placeholders so the owned output dirs exist for the agents that write to them.
for (const dir of ['reviews', 'audits', 'copy']) {
  const target = join(HERE, dir);
  mkdirSync(target, { recursive: true });
  const keep = join(target, '.gitkeep');
  if (!existsSync(keep)) writeFileSync(keep, '');
}

const repoTier = roles.filter((r) => r.tier === 'repo');
const advisory = roles.filter((r) => r.tier === 'advisory');
const guardrails = roles.filter((r) => r.guardrail);

console.log(`design-team: generated ${outputs.size} files from roster.md`);
console.log(`  subagents (.claude/agents):  ${repoTier.length} — ${repoTier.map((r) => r.slug).join(', ')}`);
console.log(`  advisory personas only:      ${advisory.length} — ${advisory.map((r) => r.slug).join(', ')}`);
console.log(`  crystl heroes (.crystl/heroes): ${roles.length} — ${guardrails.length} guardrail(s): ${guardrails.map((r) => r.slug).join(', ') || 'none'}`);
console.log(
  `  models: ${[...new Set(roles.map((r) => `${r.model}=${MODELS[r.model]}`))].sort().join(', ')}`,
);

const agentsDir = join(ROOT, '.claude/agents');
const orphans = readdirSync(agentsDir).filter(
  (f) => f.endsWith('.md') && !repoTier.some((r) => `${r.slug}.md` === f),
);
if (orphans.length) {
  console.log(`  note: unmanaged files in .claude/agents — ${orphans.join(', ')}`);
}
