/**
 * Assemble the self-contained `use_figma` push program from the tokens build output.
 *
 * Reads @auxiliary/tokens' `dist/figma-native.json` (the collections/variables contract)
 * and `dist/tokens.json` (shadows → Effect Styles), inlines them as `DATA` + `SHADOWS`,
 * and writes `dist/push.figma.js` — the program the figma-sync skill feeds to `use_figma`.
 *
 * Run after building tokens: `pnpm --filter @auxiliary/tokens build` then this.
 */
import { readFileSync, writeFileSync, mkdirSync, statSync, readdirSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { PUSH_PROGRAM } from './push-logic.mjs';
import { PULL_PROGRAM } from './pull-logic.mjs';
import { COMPONENTS_PROGRAM } from './components-logic.mjs';
import { buildComponentSpec } from './component-spec.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const tokensDir = resolve(here, '..', '..', 'tokens');
const tokensDist = resolve(tokensDir, 'dist');
const outDir = resolve(here, '..', 'dist');

// Freshness guard: this build INLINES whatever sits in tokens/dist — a stale
// artifact gets silently baked in and pushed to Figma. Under `turbo run build`
// the ^build dependency orders tokens first; this protects the documented
// standalone flow (`pnpm --filter @auxiliary/figma-sync build`).
const newestMtime = (dir) => {
  let newest = 0;
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const p = join(dir, entry.name);
    newest = Math.max(newest, entry.isDirectory() ? newestMtime(p) : statSync(p).mtimeMs);
  }
  return newest;
};
let distMtime;
try {
  distMtime = statSync(resolve(tokensDist, 'figma-native.json')).mtimeMs;
} catch {
  console.error('✗ @auxiliary/tokens has no dist/figma-native.json — run `pnpm --filter @auxiliary/tokens build` first.');
  process.exit(1);
}
if (newestMtime(resolve(tokensDir, 'src')) > distMtime) {
  console.error(
    '✗ @auxiliary/tokens dist is older than its src — the push program would inline stale tokens.\n' +
      '  Run `pnpm --filter @auxiliary/tokens build` first (or build via turbo, which orders it).',
  );
  process.exit(1);
}

const figmaNative = JSON.parse(readFileSync(resolve(tokensDist, 'figma-native.json'), 'utf8'));
const tokens = JSON.parse(readFileSync(resolve(tokensDist, 'tokens.json'), 'utf8'));

/** DTCG shadow layer → Figma DROP_SHADOW effect. */
function toEffect(layer) {
  const [r, g, b] = layer.color.components;
  return {
    type: 'DROP_SHADOW',
    color: { r, g, b, a: layer.color.alpha ?? 1 },
    offset: { x: layer.offsetX.value, y: layer.offsetY.value },
    radius: layer.blur.value,
    spread: layer.spread?.value ?? 0,
    visible: true,
    blendMode: 'NORMAL',
  };
}

/** Compact COLOR transport: {r,g,b,a} → "#rrggbb"(+aa). Decoded back in the plugin. */
function rgbaToHex(c) {
  const h = (n) => Math.round(Math.max(0, Math.min(1, n)) * 255).toString(16).padStart(2, '0');
  return '#' + h(c.r) + h(c.g) + h(c.b) + ((c.a ?? 1) < 1 ? h(c.a) : '');
}
for (const coll of figmaNative.collections) {
  for (const v of coll.variables) {
    if (v.type !== 'COLOR') continue;
    for (const mode of Object.keys(v.valuesByMode)) {
      const val = v.valuesByMode[mode];
      if (val && typeof val === 'object' && 'r' in val) v.valuesByMode[mode] = rgbaToHex(val);
    }
  }
}

/** Build { "shadow/sm": [effect, …], … } from the shadow tokens. */
// Resolve the shadow group across both DTCG tier layouts (GTC `global.shadow`,
// pre-GTC bare `shadow`). This file already models "fail loudly rather than push
// stale data" (see the dist freshness guard above); a bare `?? {}` here would
// push ZERO Effect Styles and still exit 0 if the tier layout moved — silent,
// and nobody reads the `effect styles []` line.
const shadowTokens = tokens.global?.shadow ?? tokens.shadow;
if (!shadowTokens || Object.keys(shadowTokens).length === 0) {
  console.error(
    '✗ no shadow tokens in dist/tokens.json (looked at `global.shadow` and `shadow`) — did the DTCG tier layout change?',
  );
  process.exit(1);
}
const shadows = {};
for (const [name, token] of Object.entries(shadowTokens)) {
  const layers = Array.isArray(token.$value) ? token.$value : [token.$value];
  shadows[`shadow/${name}`] = layers.map(toEffect);
}

/** Typography roles → Figma Text Styles (resolved in tokens build; passed through). */
const textStyles = figmaNative.textStyles ?? [];

const program =
  `// GENERATED by @auxiliary/figma-sync — do not edit. Run via the Figma MCP use_figma tool.\n` +
  `const DATA = ${JSON.stringify(figmaNative)};\n` +
  `const SHADOWS = ${JSON.stringify(shadows)};\n` +
  `const TEXTSTYLES = ${JSON.stringify(textStyles)};\n` +
  PUSH_PROGRAM;

mkdirSync(outDir, { recursive: true });
writeFileSync(resolve(outDir, 'push.figma.js'), program);

/**
 * Chunked payloads for the MCP path.
 *
 * `use_figma` caps its `code` argument at 50 000 characters, and the full program is
 * comfortably past that once the component tier landed. The push is idempotent and
 * matches on name, and `byQualified` is seeded from the variables already in the file,
 * so the same program can be applied as several smaller payloads in sequence with no
 * loss of cross-collection alias resolution. The single-file program above is still
 * what the dev-plugin fallback uses, where no size limit applies.
 */
const CODE_LIMIT = 50_000;
const BUDGET = 44_000; // headroom for the runtime program + the wrapper's own overhead

const chunkPayloads = [];
for (const coll of figmaNative.collections) {
  let part = [];
  for (const v of coll.variables) {
    part.push(v);
    if (JSON.stringify(part).length > BUDGET - PUSH_PROGRAM.length / 2) {
      chunkPayloads.push({ ...coll, variables: part });
      part = [];
    }
  }
  if (part.length) chunkPayloads.push({ ...coll, variables: part });
}

const chunkFiles = chunkPayloads.map((coll, i) => {
  const last = i === chunkPayloads.length - 1;
  // Styles ride along with the final chunk, once every variable exists to bind to.
  const src =
    `// GENERATED by @auxiliary/figma-sync — chunk ${i + 1}/${chunkPayloads.length} (${coll.name}). Apply in order.\n` +
    `const DATA = ${JSON.stringify({ collections: [coll] })};\n` +
    `const SHADOWS = ${JSON.stringify(last ? shadows : {})};\n` +
    `const TEXTSTYLES = ${JSON.stringify(last ? textStyles : [])};\n` +
    PUSH_PROGRAM;
  const name = `push.${String(i + 1).padStart(2, '0')}.${coll.name.toLowerCase()}.js`;
  writeFileSync(resolve(outDir, name), src);
  if (src.length > CODE_LIMIT) {
    console.error(`✗ ${name} is ${src.length} chars — over use_figma's ${CODE_LIMIT} limit.`);
    process.exit(1);
  }
  return { name, chars: src.length, vars: coll.variables.length };
});

/**
 * Pull programs — the read half (see src/pull-logic.mjs).
 *
 * The push chunks because its CODE exceeds use_figma's 50k limit once the data is
 * inlined. The pull inlines nothing, so its code is tiny; what strains the transport is
 * the RESPONSE — ~617 variables of JSON coming back. So it chunks by collection for the
 * same reason with the opposite cause, and each payload still resolves alias targets
 * into collections it did not return (pull-logic builds its id→name map over the whole
 * file, not the payload).
 *
 * Styles ride with the last payload, mirroring the push.
 */
const pullProgram = (want, includeStyles) =>
  `// GENERATED by @auxiliary/figma-sync — do not edit. Read-only; run via use_figma.\n` +
  `// Paginate by editing OFFSET/LIMIT if the response comes back with more: true.\n` +
  `const WANT = ${JSON.stringify(want)};\n` +
  `const INCLUDE_STYLES = ${includeStyles};\n` +
  `const OFFSET = 0;\n` +
  `const LIMIT = 0;\n` +
  PULL_PROGRAM;

writeFileSync(resolve(outDir, 'pull.figma.js'), pullProgram(null, true));

const pullFiles = figmaNative.collections.map((coll, i) => {
  const last = i === figmaNative.collections.length - 1;
  const name = `pull.${String(i + 1).padStart(2, '0')}.${coll.name.toLowerCase()}.js`;
  const src = pullProgram([coll.name], last);
  writeFileSync(resolve(outDir, name), src);
  if (src.length > CODE_LIMIT) {
    console.error(`✗ ${name} is ${src.length} chars — over use_figma's ${CODE_LIMIT} limit.`);
    process.exit(1);
  }
  return name;
});

/**
 * The complete expected side, in one file, for `bin/figma-diff.mjs`.
 *
 * The comparator needs the shadow Effect Styles too, and those are DERIVED here (from
 * dist/tokens.json via toEffect) rather than carried in figma-native.json. Emitting the
 * union means the CLI reads one artifact and cannot pick up a shadow map built by
 * slightly different code — the failure mode where the diff reports style drift that
 * only exists between two copies of our own derivation.
 */
writeFileSync(
  resolve(outDir, 'figma-expected.json'),
  JSON.stringify({ collections: figmaNative.collections, textStyles, shadows }, null, 2),
);

/**
 * Component sets — the second write program (see src/components-logic.mjs).
 *
 * Split into its own file rather than folded into the push because it must run AFTER
 * it: every binding addresses a variable by qualified name, and a variable that does
 * not exist yet cannot be bound. Running them as one program would work today and
 * break the moment the combined code crossed the 50k limit, in a way that looked like
 * a component styling bug rather than an ordering one.
 *
 * Chunked per component set for the same reason the push chunks.
 */
const schemaPath = resolve(here, '..', '..', 'css', 'component-schema.json');
let componentFiles = [];
try {
  const schema = JSON.parse(readFileSync(schemaPath, 'utf8'));
  const { spec, skipped } = buildComponentSpec(schema);
  for (const line of skipped) console.warn(`  ! component skipped — ${line}`);

  // Only the per-set payloads are gated on the MCP limit. The combined file is the
  // dev-plugin path, where no limit applies — same arrangement as push.figma.js, which
  // is likewise over 50k and likewise fine.
  const emitComponents = (subset, name, gate) => {
    const src =
      `// GENERATED by @auxiliary/figma-sync — do not edit. Run AFTER push.figma.js.\n` +
      `const SPEC = ${JSON.stringify(subset)};\n` +
      COMPONENTS_PROGRAM;
    writeFileSync(resolve(outDir, name), src);
    if (gate && src.length > CODE_LIMIT) {
      console.error(`✗ ${name} is ${src.length} chars — over use_figma's ${CODE_LIMIT} limit.`);
      process.exit(1);
    }
    return { name, chars: src.length };
  };

  emitComponents(spec, 'push-components.figma.js', false);
  componentFiles = Object.entries(spec).map(([setName, set], i) =>
    emitComponents(
      { [setName]: set },
      `push-components.${String(i + 1).padStart(2, '0')}.${setName.toLowerCase()}.js`,
      true,
    ),
  );
  const variants = Object.values(spec).reduce((n, s) => n + s.variants.length, 0);
  console.log(
    `✓ dist/push-components.figma.js — ${Object.keys(spec).length} component sets, ${variants} variants`,
  );
} catch (err) {
  if (err.code !== 'ENOENT') throw err;
  console.error(
    '✗ packages/css/component-schema.json is missing — run `pnpm --filter @auxiliary/css build` first.',
  );
  process.exit(1);
}

const counts = figmaNative.collections.map((c) => `${c.name}:${c.variables.length}`).join(', ');
console.log(
  `✓ dist/push.figma.js — collections [${counts}], ` +
    `effect styles [${Object.keys(shadows).join(', ')}], ` +
    `text styles [${textStyles.length}]`,
);
console.log(
  `✓ ${chunkFiles.length} MCP chunks: ` + chunkFiles.map((c) => `${c.name} (${c.chars})`).join(', '),
);
console.log(`✓ dist/pull.figma.js + ${pullFiles.length} per-collection reads: ${pullFiles.join(', ')}`);
console.log(
  `✓ ${componentFiles.length} per-set component payloads: ` + componentFiles.map((f) => f.name).join(', '),
);
console.log('✓ dist/figma-expected.json — the contract bin/figma-diff.mjs compares against');
