/**
 * Assemble the self-contained `use_figma` push program from the tokens build output.
 *
 * Reads @auxiliary/tokens' `dist/figma-native.json` (the collections/variables contract)
 * and `dist/tokens.json` (shadows → Effect Styles), inlines them as `DATA` + `SHADOWS`,
 * and writes `dist/push.figma.js` — the program the figma-sync skill feeds to `use_figma`.
 *
 * Run after building tokens: `pnpm --filter @auxiliary/tokens build` then this.
 */
import { readFileSync, writeFileSync, mkdirSync, statSync, readdirSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { PUSH_PROGRAM } from './push-logic.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const tokensDir = resolve(here, '..', '..', 'tokens');
const tokensDist = resolve(tokensDir, 'dist');
const outDir = resolve(here, '..', 'dist');

// Freshness guard: this build INLINES whatever sits in tokens/dist — a stale
// artifact gets silently baked in and pushed to Figma. Under `turbo run build`
// the ^build dependency orders tokens first; this protects the documented
// standalone flow (`pnpm --filter @auxiliary/figma-sync build`).
const newestMtime = (dir) => {
  let newest = 0;
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const p = join(dir, entry.name);
    newest = Math.max(newest, entry.isDirectory() ? newestMtime(p) : statSync(p).mtimeMs);
  }
  return newest;
};
let distMtime;
try {
  distMtime = statSync(resolve(tokensDist, 'figma-native.json')).mtimeMs;
} catch {
  console.error('✗ @auxiliary/tokens has no dist/figma-native.json — run `pnpm --filter @auxiliary/tokens build` first.');
  process.exit(1);
}
if (newestMtime(resolve(tokensDir, 'src')) > distMtime) {
  console.error(
    '✗ @auxiliary/tokens dist is older than its src — the push program would inline stale tokens.\n' +
      '  Run `pnpm --filter @auxiliary/tokens build` first (or build via turbo, which orders it).',
  );
  process.exit(1);
}

const figmaNative = JSON.parse(readFileSync(resolve(tokensDist, 'figma-native.json'), 'utf8'));
const tokens = JSON.parse(readFileSync(resolve(tokensDist, 'tokens.json'), 'utf8'));

/** DTCG shadow layer → Figma DROP_SHADOW effect. */
function toEffect(layer) {
  const [r, g, b] = layer.color.components;
  return {
    type: 'DROP_SHADOW',
    color: { r, g, b, a: layer.color.alpha ?? 1 },
    offset: { x: layer.offsetX.value, y: layer.offsetY.value },
    radius: layer.blur.value,
    spread: layer.spread?.value ?? 0,
    visible: true,
    blendMode: 'NORMAL',
  };
}

/** Compact COLOR transport: {r,g,b,a} → "#rrggbb"(+aa). Decoded back in the plugin. */
function rgbaToHex(c) {
  const h = (n) => Math.round(Math.max(0, Math.min(1, n)) * 255).toString(16).padStart(2, '0');
  return '#' + h(c.r) + h(c.g) + h(c.b) + ((c.a ?? 1) < 1 ? h(c.a) : '');
}
for (const coll of figmaNative.collections) {
  for (const v of coll.variables) {
    if (v.type !== 'COLOR') continue;
    for (const mode of Object.keys(v.valuesByMode)) {
      const val = v.valuesByMode[mode];
      if (val && typeof val === 'object' && 'r' in val) v.valuesByMode[mode] = rgbaToHex(val);
    }
  }
}

/** Build { "shadow/sm": [effect, …], … } from the shadow tokens. */
const shadows = {};
for (const [name, token] of Object.entries(tokens.shadow ?? {})) {
  const layers = Array.isArray(token.$value) ? token.$value : [token.$value];
  shadows[`shadow/${name}`] = layers.map(toEffect);
}

/** Typography roles → Figma Text Styles (resolved in tokens build; passed through). */
const textStyles = figmaNative.textStyles ?? [];

const program =
  `// GENERATED by @auxiliary/figma-sync — do not edit. Run via the Figma MCP use_figma tool.\n` +
  `const DATA = ${JSON.stringify(figmaNative)};\n` +
  `const SHADOWS = ${JSON.stringify(shadows)};\n` +
  `const TEXTSTYLES = ${JSON.stringify(textStyles)};\n` +
  PUSH_PROGRAM;

mkdirSync(outDir, { recursive: true });
writeFileSync(resolve(outDir, 'push.figma.js'), program);

const counts = figmaNative.collections.map((c) => `${c.name}:${c.variables.length}`).join(', ');
console.log(
  `✓ dist/push.figma.js — collections [${counts}], ` +
    `effect styles [${Object.keys(shadows).join(', ')}], ` +
    `text styles [${textStyles.length}]`,
);
