/**
 * sync-fonts.mjs — vendor self-hosted webfonts into @auxiliary/css.
 *
 * Air-gap-first (README Principle / ROADMAP cross-cutting): the published
 * @auxiliary/css tarball must carry its own fonts. No runtime CDN, and no
 * reliance on a separate font package being present in the consumer's offline
 * npm mirror. So we copy the woff2 + generate @font-face CSS into ./fonts/,
 * which package.json "files" ships verbatim alongside theme.css.
 *
 * Source of truth for the binaries: the @fontsource-variable/* devDependencies.
 * Re-run `pnpm --filter @auxiliary/css fonts:sync` after bumping them to
 * re-vendor. The committed ./fonts/ output is what actually ships.
 *
 * Subsets are intentionally limited (audit-minimal, smaller tarball). Add more
 * to SUBSETS below if a surface needs them.
 */
import { readFileSync, writeFileSync, mkdirSync, copyFileSync, rmSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const pkgRoot = resolve(here, '..');
const outDir = resolve(pkgRoot, 'fonts');
const outFilesDir = resolve(outDir, 'files');

/** Unicode subsets to vendor, in load-priority order. */
const SUBSETS = ['latin', 'latin-ext', 'cyrillic', 'cyrillic-ext'];

/**
 * Each family: where to read Fontsource's generated CSS (the axis-aware entry),
 * the file-name prefix used in its woff2, and the family name to EMIT.
 * We rename Geist's 'Geist Mono Variable' → 'Geist Mono' to match the
 * --font-mono token (typography.tokens.json); a mismatch silently falls back.
 */
const FAMILIES = [
  {
    name: 'Inter',
    pkg: '@fontsource-variable/inter',
    css: 'opsz.css', // opsz + wght axes — design system uses optical sizing
    filePrefix: 'inter',
    fileSuffix: '-opsz-normal.woff2',
    emitFamily: 'Inter Variable', // already matches --font-sans token
  },
  {
    name: 'Geist Mono',
    pkg: '@fontsource-variable/geist-mono',
    css: 'index.css', // wght axis
    filePrefix: 'geist-mono',
    fileSuffix: '-wght-normal.woff2',
    emitFamily: 'Geist Mono', // renamed from 'Geist Mono Variable' to match --font-mono token
  },
];

const require = (p) => resolve(pkgRoot, 'node_modules', p);

/** Split a Fontsource CSS file into { subset, block } entries. */
function parseFaces(cssText, filePrefix, fileSuffix) {
  const faces = [];
  const re = /@font-face\s*\{[^}]*\}/g;
  for (const match of cssText.match(re) ?? []) {
    const urlMatch = match.match(/url\(\.\/files\/([^)]+?\.woff2)\)/);
    if (!urlMatch) continue;
    const file = urlMatch[1];
    // file = `${filePrefix}-${subset}${fileSuffix}` → recover exact subset
    if (!file.startsWith(`${filePrefix}-`) || !file.endsWith(fileSuffix)) continue;
    const subset = file.slice(filePrefix.length + 1, file.length - fileSuffix.length);
    faces.push({ subset, file, block: match });
  }
  return faces;
}

rmSync(outDir, { recursive: true, force: true });
mkdirSync(outFilesDir, { recursive: true });

const chunks = [
  '/**',
  ' * Vendored self-hosted webfonts for @auxiliary/css. GENERATED by',
  ' * scripts/sync-fonts.mjs — do not edit by hand; re-run `pnpm fonts:sync`.',
  ' *',
  ` * Subsets: ${SUBSETS.join(', ')}. Fonts are SIL OFL-1.1 (see ./LICENSE-*.txt).`,
  ' * Air-gap: every url() below resolves inside this package; no network.',
  ' */',
  '',
];

let total = 0;
for (const fam of FAMILIES) {
  const cssPath = require(`${fam.pkg}/${fam.css}`);
  const faces = parseFaces(readFileSync(cssPath, 'utf8'), fam.filePrefix, fam.fileSuffix);
  // Copy the OFL license that ships with each Fontsource package.
  copyFileSync(require(`${fam.pkg}/LICENSE`), resolve(outDir, `LICENSE-${fam.filePrefix}.txt`));

  chunks.push(`/* ${fam.name} — ${fam.emitFamily} */`);
  for (const subset of SUBSETS) {
    const face = faces.find((f) => f.subset === subset);
    if (!face) {
      console.warn(`  ! ${fam.name}: subset "${subset}" not found in ${fam.css} — skipped`);
      continue;
    }
    copyFileSync(require(`${fam.pkg}/files/${face.file}`), resolve(outFilesDir, face.file));
    const block = face.block.replace(
      /font-family:\s*'[^']*'/,
      `font-family: '${fam.emitFamily}'`,
    );
    chunks.push(block, '');
    total++;
  }
}

writeFileSync(resolve(outDir, 'fonts.css'), chunks.join('\n'));
console.log(`✓ vendored ${total} @font-face subsets → packages/css/fonts/`);
