/**
 * sync-fonts.mjs — vendor self-hosted webfonts into @auxiliary/css.
 *
 * Air-gap-first (README Principle / ROADMAP cross-cutting): the published
 * @auxiliary/css tarball must carry its own fonts. No runtime CDN, and no
 * reliance on a separate font package being present in the consumer's offline
 * npm mirror. So we copy the woff2 + generate @font-face CSS into ./fonts/,
 * which package.json "files" ships verbatim alongside theme.css.
 *
 * Source of truth for the binaries: the @fontsource-variable/* devDependencies.
 * Re-run `pnpm --filter @auxiliary/css fonts:sync` after bumping them to
 * re-vendor. The committed ./fonts/ output is what actually ships.
 *
 * Subsets are intentionally limited (audit-minimal, smaller tarball). Add more
 * to SUBSETS below if a surface needs them.
 */
import { readFileSync, writeFileSync, mkdirSync, copyFileSync, rmSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const pkgRoot = resolve(here, '..');
const outDir = resolve(pkgRoot, 'fonts');
const outFilesDir = resolve(outDir, 'files');

/** Unicode subsets to vendor, in load-priority order. */
const SUBSETS = ['latin', 'latin-ext', 'cyrillic', 'cyrillic-ext'];

/**
 * Each family: where to read Fontsource's generated CSS (the axis-aware entry),
 * the file-name prefix used in its woff2, and the family name to EMIT.
 * We rename Geist's 'Geist Mono Variable' → 'Geist Mono' to match the
 * --font-mono token (typography.tokens.json); a mismatch silently falls back.
 */
const FAMILIES = [
  {
    name: 'Inter',
    type: 'download',
    // Fontsource's variable builds (opsz / standard / wght) STRIP Inter's
    // stylistic sets + character variants — ssXX/cvXX are no-ops with them
    // (verified: cv05/cv12/cv13 produce zero width change). The official rsms
    // build is the only feature-complete variable woff2: it keeps the opsz +
    // wght axes AND every OpenType feature (ss06 squared, ss02 disambiguation,
    // cv01–cv13, …). One full-charset file — no per-subset splitting.
    url: 'https://rsms.me/inter/font-files/InterVariable.woff2?v=4.1',
    file: 'InterVariable.woff2',
    licensePkg: '@fontsource-variable/inter', // same font → reuse its OFL text
    emitFamily: 'Inter Variable', // matches --font-sans token
  },
  {
    name: 'Geist Mono',
    type: 'fontsource',
    pkg: '@fontsource-variable/geist-mono',
    css: 'index.css', // wght axis
    filePrefix: 'geist-mono',
    fileSuffix: '-wght-normal.woff2',
    emitFamily: 'Geist Mono', // renamed from 'Geist Mono Variable' to match --font-mono token
  },
];

const require = (p) => resolve(pkgRoot, 'node_modules', p);

/** Split a Fontsource CSS file into { subset, block } entries. */
function parseFaces(cssText, filePrefix, fileSuffix) {
  const faces = [];
  const re = /@font-face\s*\{[^}]*\}/g;
  for (const match of cssText.match(re) ?? []) {
    const urlMatch = match.match(/url\(\.\/files\/([^)]+?\.woff2)\)/);
    if (!urlMatch) continue;
    const file = urlMatch[1];
    // file = `${filePrefix}-${subset}${fileSuffix}` → recover exact subset
    if (!file.startsWith(`${filePrefix}-`) || !file.endsWith(fileSuffix)) continue;
    const subset = file.slice(filePrefix.length + 1, file.length - fileSuffix.length);
    faces.push({ subset, file, block: match });
  }
  return faces;
}

rmSync(outDir, { recursive: true, force: true });
mkdirSync(outFilesDir, { recursive: true });

const chunks = [
  '/**',
  ' * Vendored self-hosted webfonts for @auxiliary/css. GENERATED by',
  ' * scripts/sync-fonts.mjs — do not edit by hand; re-run `pnpm fonts:sync`.',
  ' *',
  ` * Inter: full charset (official feature-complete build). Geist Mono subsets: ${SUBSETS.join(', ')}.`,
  ' * Fonts are SIL OFL-1.1 (see ./LICENSE-*.txt).',
  ' * Air-gap: every url() below resolves inside this package; no network.',
  ' */',
  '',
];

let total = 0;
for (const fam of FAMILIES) {
  // Official feature-complete build, fetched at sync time and vendored locally
  // (build-time fetch only — the runtime CSS still resolves inside the package).
  if (fam.type === 'download') {
    const res = await fetch(fam.url);
    if (!res.ok) throw new Error(`fetch ${fam.url} → HTTP ${res.status}`);
    writeFileSync(resolve(outFilesDir, fam.file), Buffer.from(await res.arrayBuffer()));
    copyFileSync(require(`${fam.licensePkg}/LICENSE`), resolve(outDir, `LICENSE-inter.txt`));
    chunks.push(
      `/* ${fam.name} — ${fam.emitFamily} (official feature-complete variable build, opsz+wght) */`,
      `@font-face {`,
      `  font-family: '${fam.emitFamily}';`,
      `  font-style: normal;`,
      // `optional`, not `swap`. `swap` with no metric override is FOUT plus
      // reflow: the page paints in system-ui, then every line re-measures when
      // the 344 KB file lands, moving text under the reader's eye and finger.
      // `optional` gives the font a short block period and, if it misses, simply
      // does not swap this pageview — so the layout NEVER shifts. That trade is
      // only sane because the file is same-origin and preloaded (see PRELOAD
      // below): with both, the font wins the race on essentially every load, and
      // the failure mode degrades to "system font, once" instead of "reflow,
      // every cold load". AD-D-036 names the reflow risk and leaves it unfilled.
      `  font-display: optional;`,
      `  font-weight: 100 900;`,
      `  src: url(./files/${fam.file}) format('woff2');`,
      `}`,
      '',
    );
    total++;
    continue;
  }

  const cssPath = require(`${fam.pkg}/${fam.css}`);
  const faces = parseFaces(readFileSync(cssPath, 'utf8'), fam.filePrefix, fam.fileSuffix);
  // Copy the OFL license that ships with each Fontsource package.
  copyFileSync(require(`${fam.pkg}/LICENSE`), resolve(outDir, `LICENSE-${fam.filePrefix}.txt`));

  chunks.push(`/* ${fam.name} — ${fam.emitFamily} */`);
  for (const subset of SUBSETS) {
    const face = faces.find((f) => f.subset === subset);
    if (!face) {
      console.warn(`  ! ${fam.name}: subset "${subset}" not found in ${fam.css} — skipped`);
      continue;
    }
    copyFileSync(require(`${fam.pkg}/files/${face.file}`), resolve(outFilesDir, face.file));
    const block = face.block
      .replace(/font-family:\s*'[^']*'/, `font-family: '${fam.emitFamily}'`)
      // Same reasoning as the Inter face above — one loading policy across the
      // whole vendored set, not `optional` for the sans and `swap` for the mono.
      // A mono reflow is the worse one: it moves telemetry digits sideways while
      // an operator is reading them.
      .replace(/font-display:\s*swap/, 'font-display: optional');
    chunks.push(block, '');
    total++;
  }
}

// The browser cannot discover a font until the CSS that references it has
// parsed, which is exactly the delay `font-display: optional` is racing. Emitting
// the preload tags next to the faces keeps the two in sync — a face added here
// gets its hint automatically, instead of the hint being hand-maintained in each
// app shell and quietly going stale.
// Only the subsets on the critical path. Preloading cyrillic and latin-ext would
// pull ~3x the bytes for glyphs almost no page renders — a preload is a promise
// that the file is needed NOW, and over-promising delays the ones that are.
const preloadFiles = [
  ...new Set([...chunks.join('\n').matchAll(/url\(\.\/files\/([^)]+)\)/g)].map((m) => m[1])),
].filter((f) => !/cyrillic|latin-ext/.test(f));
writeFileSync(
  resolve(outDir, 'preload.html'),
  [
    '<!-- GENERATED by scripts/sync-fonts.mjs — do not edit by hand.',
    '     Paste into the <head> of an app shell, BEFORE the stylesheet link.',
    '     `font-display: optional` only pays off if the file is already in flight;',
    '     without these hints the font is discovered after the CSS parses and the',
    '     block period is usually missed. `crossorigin` is required even same-origin',
    '     — font fetches are CORS-mode, and without it the preload is not reused. -->',
    ...preloadFiles.map(
      (f) =>
        `<link rel="preload" as="font" type="font/woff2" crossorigin href="/fonts/files/${f}">`,
    ),
    '',
  ].join('\n'),
);

writeFileSync(resolve(outDir, 'fonts.css'), chunks.join('\n'));
console.log(`✓ vendored ${total} @font-face subsets → packages/css/fonts/`);
